#!/bin/sh

echo "\nLet me check if you can push this!"
echo "\nExecuting unit tests..."

testValidationResult=$(grunt test | grep "Done, without errors")

if [ "$testValidationResult" != "" ]; then
        echo "\033[32mUnit tests execution passed. Wow, such tests, much green!\033[0m"
else
        echo "\033[31mUnit tests execution failed. And what do we say to the god of Push? Not today! \033[0m"
        exit 1
fi

echo "\033[32mPushing...\033[0m"
